export type Track = "common" | "python" | "cpp";
export type LessonSection = "foundation" | "specialization";

export interface LessonMeta {
  id: string;
  slug: string;
  title: string;
  summary: string;
  track: Track;
  order: number;
  durationMinutes: number;
  concepts: string[];
  prerequisites?: string[];
}

export const TRACK_LABELS: Record<Track, string> = {
  common: "迁移基础",
  python: "Python / AI",
  cpp: "C++ / Robotics",
};

export const TRACK_DESCRIPTIONS: Record<Track, string> = {
  common: "把熟悉的 JS/TS 心智模型，翻译成系统语言和 AI 工具链都能用的跨语言基础。",
  python: "先完成 Python 迁移基础，再进入数据、模型和 AI 服务工程。",
  cpp: "先完成 C++ 迁移基础，再进入消息、实时性和 ROS 2 工程。",
};

export const TRACK_SECTION_LABELS: Record<Track, Record<LessonSection, string>> = {
  common: { foundation: "通用迁移基础", specialization: "" },
  python: { foundation: "Python 迁移基础", specialization: "Python / AI" },
  cpp: { foundation: "C++ 迁移基础", specialization: "C++ / Robotics" },
};

export function getLessonSection(lesson: LessonMeta): LessonSection {
  if (lesson.track === "common") return "foundation";
  // These boundaries follow the curriculum: language fundamentals first, then domain tooling.
  if (lesson.track === "python") return lesson.order <= 8 ? "foundation" : "specialization";
  return lesson.order <= 16 ? "foundation" : "specialization";
}

const commonLessons: LessonMeta[] = [
  {
    id: "common-runtime",
    slug: "runtime-and-toolchain",
    title: "运行时与工具链：从 npm 到编译器",
    summary: "理解解释执行、编译、包管理和项目入口在三种语言中的差异。",
    track: "common",
    order: 1,
    durationMinutes: 8,
    concepts: ["runtime", "toolchain", "package manager"],
  },
  {
    id: "common-values",
    slug: "values-types-and-collections",
    title: "值、类型与集合：同一个需求的三种表达",
    summary: "把对象、数组和类型系统的经验迁移到 list、vector、map 和 struct。",
    track: "common",
    order: 2,
    durationMinutes: 10,
    concepts: ["types", "objects", "arrays", "collections"],
    prerequisites: ["common-runtime"],
  },
  {
    id: "common-functions",
    slug: "functions-modules-and-errors",
    title: "函数、模块与错误处理：让代码可组合",
    summary: "比较 import/export、模块边界、返回值和异常处理的工程取舍。",
    track: "common",
    order: 3,
    durationMinutes: 10,
    concepts: ["functions", "modules", "errors"],
  },
  {
    id: "common-concurrency",
    slug: "async-concurrency-and-engineering",
    title: "异步、并发与工程习惯",
    summary: "从 Promise 和 event loop 出发，建立对线程、任务和资源生命周期的直觉。",
    track: "common",
    order: 4,
    durationMinutes: 12,
    concepts: ["async", "concurrency", "testing"],
    prerequisites: ["common-functions"],
  },
  {
    id: "common-data-models",
    slug: "data-models-and-boundaries",
    title: "数据模型与边界：对象不只是 JSON",
    summary: "理解对象、struct、class 和消息结构在跨语言项目中的职责边界。",
    track: "common",
    order: 5,
    durationMinutes: 14,
    concepts: ["data model", "struct", "class", "schema"],
    prerequisites: ["common-concurrency"],
  },
  {
    id: "common-errors",
    slug: "errors-debugging-and-logging",
    title: "错误、调试与日志：让失败可定位",
    summary: "把 try/catch、返回值、断点和结构化日志放进同一套排错流程。",
    track: "common",
    order: 6,
    durationMinutes: 14,
    concepts: ["errors", "debugging", "logging", "observability"],
    prerequisites: ["common-data-models"],
  },
  {
    id: "common-cli",
    slug: "cli-project-structure-and-config",
    title: "CLI、项目结构与配置",
    summary: "从 npm scripts 出发，掌握可测试的命令行入口、配置和目录组织。",
    track: "common",
    order: 7,
    durationMinutes: 12,
    concepts: ["cli", "project structure", "configuration", "testing"],
    prerequisites: ["common-errors"],
  },
  {
    id: "common-performance",
    slug: "performance-and-observability-basics",
    title: "性能与可观察性：先测量再优化",
    summary: "建立时间、内存、吞吐和日志指标的基本直觉，避免凭感觉优化。",
    track: "common",
    order: 24,
    durationMinutes: 14,
    concepts: ["performance", "memory", "profiling", "metrics"],
    prerequisites: ["common-observability"],
  },
  {
    id: "common-syntax",
    slug: "syntax-control-flow-and-expressions",
    title: "控制流与表达式：同一个逻辑的三种写法",
    summary: "把条件、循环和短路表达式从 JS/TS 翻译成 Python 与 C++ 的清晰写法。",
    track: "common",
    order: 8,
    durationMinutes: 12,
    concepts: ["syntax", "control flow", "expressions"],
    prerequisites: ["common-cli"],
  },
  {
    id: "common-mutability",
    slug: "mutability-identity-and-side-effects",
    title: "可变性、身份与副作用",
    summary: "理解引用、拷贝和原地修改，避免把 JavaScript 对象直觉带进其他运行时。",
    track: "common",
    order: 9,
    durationMinutes: 14,
    concepts: ["mutability", "identity", "side effects"],
    prerequisites: ["common-syntax"],
  },
  {
    id: "common-iteration",
    slug: "iteration-laziness-and-streams",
    title: "迭代、惰性与数据流",
    summary: "比较数组链、生成器、迭代器和流式处理，学会按数据规模选择实现。",
    track: "common",
    order: 10,
    durationMinutes: 14,
    concepts: ["iteration", "lazy evaluation", "streams"],
    prerequisites: ["common-mutability"],
  },
  {
    id: "common-boundaries",
    slug: "api-boundaries-and-contracts",
    title: "API 边界与契约",
    summary: "用输入、输出、不变量和失败语义定义稳定接口，而不是只传一堆对象。",
    track: "common",
    order: 11,
    durationMinutes: 14,
    concepts: ["api", "contracts", "invariants"],
    prerequisites: ["common-iteration"],
  },
  {
    id: "common-filesystem",
    slug: "filesystem-paths-and-portability",
    title: "文件系统、路径与跨平台",
    summary: "从 Node.js path 经验出发，处理路径、编码、目录和权限的跨平台差异。",
    track: "common",
    order: 12,
    durationMinutes: 14,
    concepts: ["filesystem", "paths", "portability"],
    prerequisites: ["common-boundaries"],
  },
  {
    id: "common-http",
    slug: "http-timeouts-and-retries",
    title: "HTTP、超时与重试边界",
    summary: "把 fetch 的使用经验扩展为可取消、有超时、能区分失败类型的服务调用。",
    track: "common",
    order: 13,
    durationMinutes: 16,
    concepts: ["http", "timeouts", "retries"],
    prerequisites: ["common-filesystem"],
  },
  {
    id: "common-config",
    slug: "configuration-environments-and-secrets",
    title: "配置、环境变量与密钥边界",
    summary: "让本地、测试和生产环境使用同一套配置契约，并避免把密钥写进代码。",
    track: "common",
    order: 14,
    durationMinutes: 12,
    concepts: ["configuration", "environment", "secrets"],
    prerequisites: ["common-http"],
  },
  {
    id: "common-processes",
    slug: "processes-stdio-and-exit-codes",
    title: "进程、标准输入输出与退出码",
    summary: "理解脚本、子进程和命令行工具如何通过 stdin、stdout、stderr 协作。",
    track: "common",
    order: 15,
    durationMinutes: 14,
    concepts: ["processes", "stdio", "exit codes"],
    prerequisites: ["common-config"],
  },
  {
    id: "common-tasks",
    slug: "tasks-threads-and-scheduling",
    title: "任务、线程与调度",
    summary: "区分并发、并行和异步，建立从事件循环到线程池的统一模型。",
    track: "common",
    order: 16,
    durationMinutes: 16,
    concepts: ["tasks", "threads", "scheduling"],
    prerequisites: ["common-processes"],
  },
  {
    id: "common-synchronization",
    slug: "shared-state-locks-and-queues",
    title: "共享状态、锁与消息队列",
    summary: "从竞态条件出发，比较锁、不可变消息和队列三种协作方式。",
    track: "common",
    order: 17,
    durationMinutes: 16,
    concepts: ["shared state", "locks", "queues"],
    prerequisites: ["common-tasks"],
  },
  {
    id: "common-memory",
    slug: "stack-heap-and-lifetimes",
    title: "栈、堆与对象生命周期",
    summary: "用内存布局解释闭包、引用、堆对象和显式生命周期在三种语言里的差异。",
    track: "common",
    order: 18,
    durationMinutes: 16,
    concepts: ["stack", "heap", "lifetime"],
    prerequisites: ["common-synchronization"],
  },
  {
    id: "common-serialization",
    slug: "serialization-and-versioning",
    title: "序列化、二进制与版本兼容",
    summary: "理解 JSON、二进制和消息版本演进，建立跨进程数据的兼容意识。",
    track: "common",
    order: 19,
    durationMinutes: 14,
    concepts: ["serialization", "json", "versioning"],
    prerequisites: ["common-memory"],
  },
  {
    id: "common-testing",
    slug: "testing-strategy-and-test-doubles",
    title: "测试策略与测试替身",
    summary: "把单元、集成和端到端测试分层，并学会替换时间、网络和文件依赖。",
    track: "common",
    order: 20,
    durationMinutes: 16,
    concepts: ["testing", "mocks", "integration"],
    prerequisites: ["common-serialization"],
  },
  {
    id: "common-debugging",
    slug: "debugging-workflow-and-minimal-reproduction",
    title: "调试工作流与最小复现",
    summary: "把堆栈、断点、日志和二分定位组织成一套跨语言排错流程。",
    track: "common",
    order: 21,
    durationMinutes: 14,
    concepts: ["debugging", "stack trace", "reproduction"],
    prerequisites: ["common-testing"],
  },
  {
    id: "common-observability",
    slug: "metrics-traces-and-latency",
    title: "指标、追踪与延迟",
    summary: "从“感觉变慢”升级到测量吞吐、延迟、错误率和资源使用。",
    track: "common",
    order: 22,
    durationMinutes: 14,
    concepts: ["metrics", "tracing", "latency"],
    prerequisites: ["common-debugging"],
  },
  {
    id: "common-security",
    slug: "input-validation-and-security-boundaries",
    title: "输入校验与安全边界",
    summary: "识别不可信输入、命令注入、路径穿越和过度信任类型提示的风险。",
    track: "common",
    order: 23,
    durationMinutes: 16,
    concepts: ["validation", "security", "untrusted input"],
    prerequisites: ["common-observability"],
  },
  {
    id: "common-architecture",
    slug: "modularity-and-dependency-inversion",
    title: "模块化与跨语言架构",
    summary: "把业务规则、IO、设备和外部服务拆开，让代码可以单独测试、替换和跨语言协作。",
    track: "common",
    order: 25,
    durationMinutes: 16,
    concepts: ["architecture", "modularity", "dependency inversion", "interop"],
    prerequisites: ["common-performance"],
  },
  {
    id: "common-capstone",
    slug: "cross-language-data-contract-project",
    title: "综合项目：跨语言数据契约",
    summary: "设计一个 JS/TS 生产数据、Python 清洗、C++ 消费的可演进消息契约。",
    track: "common",
    order: 26,
    durationMinutes: 24,
    concepts: ["capstone", "data contract", "interop"],
    prerequisites: ["common-architecture"],
  },
];

const pythonLessons: LessonMeta[] = [
  {
    id: "python-syntax",
    slug: "python-syntax-and-data-model",
    title: "Python 语法与数据模型",
    summary: "用 JS/TS 的已知概念快速掌握 Python 的缩进、可变性和常用容器。",
    track: "python",
    order: 1,
    durationMinutes: 10,
    concepts: ["syntax", "mutability", "dict", "list"],
  },
  {
    id: "python-functions",
    slug: "functions-modules-and-types",
    title: "函数、模块与类型提示",
    summary: "把 TypeScript 的类型思维迁移到 Python 函数、模块和 type hints。",
    track: "python",
    order: 3,
    durationMinutes: 10,
    concepts: ["functions", "modules", "typing"],
    prerequisites: ["python-control-flow"],
  },
  {
    id: "python-packaging",
    slug: "environments-and-packaging",
    title: "虚拟环境与依赖管理",
    summary: "从 node_modules 的经验出发，理解虚拟环境、依赖锁定和可复现运行。",
    track: "python",
    order: 6,
    durationMinutes: 8,
    concepts: ["venv", "dependencies", "reproducibility"],
    prerequisites: ["python-iterators"],
  },
  {
    id: "python-files",
    slug: "files-http-and-data-pipelines",
    title: "文件、HTTP 与数据管线",
    summary: "把 Node.js 脚本迁移成清晰的 Python 数据处理流程。",
    track: "python",
    order: 7,
    durationMinutes: 12,
    concepts: ["files", "http", "json", "pipelines"],
    prerequisites: ["python-packaging"],
  },
  {
    id: "python-testing",
    slug: "testing-and-debugging",
    title: "测试、调试与可观察性",
    summary: "用 pytest 思维建立输入、输出和失败路径的可靠边界。",
    track: "python",
    order: 8,
    durationMinutes: 10,
    concepts: ["testing", "debugging", "logging"],
    prerequisites: ["python-files"],
  },
  {
    id: "python-data",
    slug: "ai-data-inputs",
    title: "AI 数据输入：从 JSON 到特征表",
    summary: "理解 AI 应用前的数据清洗、结构化和输入校验。",
    track: "python",
    order: 16,
    durationMinutes: 12,
    concepts: ["data", "validation", "ai", "json"],
    prerequisites: ["python-iterators"],
  },
  {
    id: "python-oop",
    slug: "object-model-and-dataclasses",
    title: "对象模型、类与 dataclass",
    summary: "把 TypeScript class、interface 和对象组合经验迁移到 Python 数据对象。",
    track: "python",
    order: 4,
    durationMinutes: 14,
    concepts: ["classes", "dataclass", "composition", "protocol"],
    prerequisites: ["python-functions"],
  },
  {
    id: "python-iterators",
    slug: "iterators-generators-and-context-managers",
    title: "迭代器、生成器与上下文管理",
    summary: "理解 Python 如何延迟处理数据，并用 with 安全管理文件和外部资源。",
    track: "python",
    order: 5,
    durationMinutes: 16,
    concepts: ["iterators", "generators", "context manager", "streaming"],
    prerequisites: ["python-oop"],
  },
  {
    id: "python-numpy",
    slug: "numpy-arrays-and-vectorized-thinking",
    title: "NumPy 数组与向量化思维",
    summary: "从 JavaScript 数组进入 AI 常用的批量数据、形状和向量化操作。",
    track: "python",
    order: 18,
    durationMinutes: 16,
    concepts: ["numpy", "arrays", "shape", "vectorization"],
    prerequisites: ["python-data"],
  },
  {
    id: "python-async",
    slug: "async-services-and-retries",
    title: "异步服务、超时与重试",
    summary: "将 Promise 的经验迁移到 asyncio，并为 AI 服务调用补上超时和重试边界。",
    track: "python",
    order: 13,
    durationMinutes: 16,
    concepts: ["asyncio", "http", "timeout", "retry"],
    prerequisites: ["python-concurrency"],
  },
  {
    id: "python-project",
    slug: "project-data-preparation-cli",
    title: "小项目：构建一个数据准备 CLI",
    summary: "把前面的迁移知识组合成一个可测试、可扩展的数据准备命令行工具。",
    track: "python",
    order: 30,
    durationMinutes: 18,
    concepts: ["project", "cli", "ai", "testing"],
    prerequisites: ["python-mlops"],
  },
  {
    id: "python-control-flow",
    slug: "control-flow-and-comprehensions",
    title: "控制流、推导式与可读性",
    summary: "把 JS/TS 的条件、循环和数组链改写成 Python 的清晰表达。",
    track: "python",
    order: 2,
    durationMinutes: 12,
    concepts: ["control flow", "comprehensions", "readability"],
    prerequisites: ["python-syntax"],
  },
  {
    id: "python-http",
    slug: "http-clients-and-service-boundaries",
    title: "HTTP 客户端与服务边界",
    summary: "使用 Python 调用外部服务，并区分网络失败、业务失败和数据校验失败。",
    track: "python",
    order: 9,
    durationMinutes: 16,
    concepts: ["http", "clients", "validation"],
    prerequisites: ["python-testing"],
  },
  {
    id: "python-cli",
    slug: "cli-arguments-and-configuration",
    title: "CLI 参数与配置入口",
    summary: "将 npm scripts 迁移到 argparse，让命令行工具具备帮助信息和可测试入口。",
    track: "python",
    order: 10,
    durationMinutes: 14,
    concepts: ["cli", "argparse", "configuration"],
    prerequisites: ["python-http"],
  },
  {
    id: "python-logging",
    slug: "logging-errors-and-observability",
    title: "日志、错误与可观察性",
    summary: "建立结构化日志、异常边界和调试上下文，知道服务到底在哪里失败。",
    track: "python",
    order: 11,
    durationMinutes: 14,
    concepts: ["logging", "exceptions", "observability"],
    prerequisites: ["python-cli"],
  },
  {
    id: "python-concurrency",
    slug: "threads-processes-and-asyncio",
    title: "线程、进程与 asyncio",
    summary: "从 Promise 和 event loop 出发，理解 Python 任务、线程和进程的适用场景。",
    track: "python",
    order: 12,
    durationMinutes: 18,
    concepts: ["asyncio", "threads", "processes"],
    prerequisites: ["python-logging"],
  },
  {
    id: "python-sql",
    slug: "sql-and-data-access",
    title: "SQL 与数据访问",
    summary: "用 Python 读取结构化数据，理解查询边界、参数化和连接资源管理。",
    track: "python",
    order: 14,
    durationMinutes: 16,
    concepts: ["sql", "database", "parameterization"],
    prerequisites: ["python-async"],
  },
  {
    id: "python-data-models",
    slug: "schemas-validation-and-data-contracts",
    title: "Schema、校验与数据契约",
    summary: "把动态 JSON 转成可检查的数据模型，为 AI 输入建立明确边界。",
    track: "python",
    order: 15,
    durationMinutes: 16,
    concepts: ["schema", "validation", "data contracts"],
    prerequisites: ["python-sql"],
  },
  {
    id: "python-pandas",
    slug: "pandas-dataframes-and-cleaning",
    title: "pandas DataFrame 与数据清洗",
    summary: "从 JavaScript 数组对象进入表格数据、缺失值、分组和合并操作。",
    track: "python",
    order: 17,
    durationMinutes: 18,
    concepts: ["pandas", "dataframe", "cleaning"],
    prerequisites: ["python-data"],
  },
  {
    id: "python-numpy-linear",
    slug: "numpy-broadcasting-and-linear-algebra",
    title: "NumPy 广播与线性代数",
    summary: "掌握 shape、axis、broadcasting 和矩阵操作，避免逐元素循环拖慢数据处理。",
    track: "python",
    order: 19,
    durationMinutes: 18,
    concepts: ["numpy", "broadcasting", "linear algebra"],
    prerequisites: ["python-numpy"],
  },
  {
    id: "python-visualization",
    slug: "visualization-and-data-diagnostics",
    title: "可视化与数据诊断",
    summary: "用分布、异常值和分组图检查数据，而不是直接把脏数据送进模型。",
    track: "python",
    order: 20,
    durationMinutes: 16,
    concepts: ["visualization", "eda", "outliers"],
    prerequisites: ["python-numpy-linear"],
  },
  {
    id: "python-scikit",
    slug: "baselines-metrics-and-scikit-learn",
    title: "基线模型、指标与 scikit-learn",
    summary: "先建立可解释的 baseline，再选择模型和指标，而不是一开始就追求复杂网络。",
    track: "python",
    order: 21,
    durationMinutes: 18,
    concepts: ["baseline", "metrics", "scikit-learn"],
    prerequisites: ["python-visualization"],
  },
  {
    id: "python-datasets",
    slug: "dataset-splits-and-leakage",
    title: "数据集切分、泄漏与可复现",
    summary: "区分训练、验证和测试数据，识别 data leakage 并固定随机性。",
    track: "python",
    order: 22,
    durationMinutes: 18,
    concepts: ["datasets", "leakage", "reproducibility"],
    prerequisites: ["python-scikit"],
  },
  {
    id: "python-pytorch-tensors",
    slug: "pytorch-tensors-and-autograd",
    title: "PyTorch Tensor 与 autograd",
    summary: "从 NumPy 数组迁移到 Tensor、设备和自动微分，理解训练为何需要梯度。",
    track: "python",
    order: 23,
    durationMinutes: 18,
    concepts: ["pytorch", "tensors", "autograd"],
    prerequisites: ["python-datasets"],
  },
  {
    id: "python-pytorch-models",
    slug: "pytorch-models-and-training-loops",
    title: "PyTorch 模型与训练循环",
    summary: "拆解 Module、loss、optimizer 和 epoch，建立能调试的最小训练循环。",
    track: "python",
    order: 24,
    durationMinutes: 20,
    concepts: ["nn.Module", "loss", "optimizer"],
    prerequisites: ["python-pytorch-tensors"],
  },
  {
    id: "python-pytorch-data",
    slug: "pytorch-datasets-and-dataloaders",
    title: "Dataset、DataLoader 与批处理",
    summary: "把样本读取、变换、batch 和 worker 组织成稳定的数据输入管线。",
    track: "python",
    order: 25,
    durationMinutes: 18,
    concepts: ["dataset", "dataloader", "batching"],
    prerequisites: ["python-pytorch-models"],
  },
  {
    id: "python-pytorch-evaluation",
    slug: "evaluation-checkpoints-and-experiments",
    title: "评估、checkpoint 与实验记录",
    summary: "保存最佳模型、记录指标和比较实验，避免只凭最后一次训练结果下结论。",
    track: "python",
    order: 26,
    durationMinutes: 18,
    concepts: ["evaluation", "checkpoint", "experiments"],
    prerequisites: ["python-pytorch-data"],
  },
  {
    id: "python-inference",
    slug: "model-inference-and-batching",
    title: "模型推理、批量与资源边界",
    summary: "把训练代码改成稳定推理入口，处理 eval 模式、batch、CPU/GPU 和超时。",
    track: "python",
    order: 27,
    durationMinutes: 18,
    concepts: ["inference", "batching", "deployment"],
    prerequisites: ["python-pytorch-evaluation"],
  },
  {
    id: "python-deployment",
    slug: "model-api-and-service-deployment",
    title: "模型 API 与服务部署",
    summary: "将推理能力包装成 HTTP API，补齐输入校验、健康检查和版本信息。",
    track: "python",
    order: 28,
    durationMinutes: 18,
    concepts: ["api", "health check", "serving"],
    prerequisites: ["python-inference"],
  },
  {
    id: "python-mlops",
    slug: "experiment-configs-and-model-monitoring",
    title: "实验配置与模型监控",
    summary: "用配置、数据版本和输入分布监控把一次实验变成可维护的工程流程。",
    track: "python",
    order: 29,
    durationMinutes: 18,
    concepts: ["mlops", "configuration", "monitoring"],
    prerequisites: ["python-deployment"],
  },
];

const cppLessons: LessonMeta[] = [
  {
    id: "cpp-toolchain",
    slug: "compile-link-and-cmake",
    title: "编译、链接与 CMake",
    summary: "把 bundler 和运行时的经验转换成 C++ 的编译产物和构建目标。",
    track: "cpp",
    order: 1,
    durationMinutes: 12,
    concepts: ["compiler", "linker", "cmake"],
  },
  {
    id: "cpp-values",
    slug: "values-references-and-pointers",
    title: "值、引用与指针",
    summary: "用可视化的内存直觉理解 C++ 为什么需要引用和指针。",
    track: "cpp",
    order: 4,
    durationMinutes: 14,
    concepts: ["memory", "references", "pointers"],
    prerequisites: ["cpp-toolchain"],
  },
  {
    id: "cpp-stl",
    slug: "stl-containers-and-algorithms",
    title: "STL 容器与算法",
    summary: "把 Array、Map 和高阶函数经验迁移到 vector、unordered_map 和算法。",
    track: "cpp",
    order: 6,
    durationMinutes: 12,
    concepts: ["stl", "vector", "algorithms"],
    prerequisites: ["cpp-values"],
  },
  {
    id: "cpp-raii",
    slug: "raii-and-smart-pointers",
    title: "RAII 与智能指针",
    summary: "理解资源生命周期，避免把 JavaScript 的垃圾回收直觉硬套到 C++。",
    track: "cpp",
    order: 8,
    durationMinutes: 14,
    concepts: ["raii", "ownership", "smart pointers"],
    prerequisites: ["cpp-stl"],
  },
  {
    id: "cpp-interfaces",
    slug: "classes-interfaces-and-errors",
    title: "类、接口与错误处理",
    summary: "比较 TypeScript interface、C++ class 和显式错误返回的边界。",
    track: "cpp",
    order: 10,
    durationMinutes: 12,
    concepts: ["classes", "interfaces", "errors"],
    prerequisites: ["cpp-move"],
  },
  {
    id: "cpp-functions",
    slug: "functions-headers-and-linkage",
    title: "函数、头文件与链接边界",
    summary: "理解声明、定义、头文件和链接错误，建立 C++ 多文件项目的基础。",
    track: "cpp",
    order: 5,
    durationMinutes: 14,
    concepts: ["functions", "headers", "linkage", "namespaces"],
    prerequisites: ["cpp-values"],
  },
  {
    id: "cpp-templates",
    slug: "templates-and-generic-algorithms",
    title: "模板与泛型算法",
    summary: "把 TypeScript 泛型的经验迁移到 C++ 模板、类型推导和可复用算法。",
    track: "cpp",
    order: 12,
    durationMinutes: 16,
    concepts: ["templates", "generics", "type deduction", "algorithms"],
    prerequisites: ["cpp-interfaces"],
  },
  {
    id: "cpp-testing",
    slug: "cmake-testing-and-debugging",
    title: "CMake 测试与调试",
    summary: "把 C++ 代码拆成可测试目标，并用断点、断言和 Sanitizer 找到内存问题。",
    track: "cpp",
    order: 16,
    durationMinutes: 16,
    concepts: ["cmake", "testing", "debugging", "sanitizer"],
    prerequisites: ["cpp-cmake-targets"],
  },
  {
    id: "cpp-concurrency",
    slug: "threads-and-message-loops",
    title: "线程与消息循环",
    summary: "从事件循环出发，建立机器人消息处理与线程同步的基础模型。",
    track: "cpp",
    order: 18,
    durationMinutes: 14,
    concepts: ["threads", "messages", "concurrency"],
    prerequisites: ["cpp-sanitizers"],
  },
  {
    id: "cpp-performance",
    slug: "memory-layout-and-performance",
    title: "内存布局与性能测量",
    summary: "理解缓存、拷贝、移动和基准测试，为机器人实时处理建立性能判断。",
    track: "cpp",
    order: 21,
    durationMinutes: 16,
    concepts: ["memory", "cache", "move", "benchmark"],
    prerequisites: ["cpp-queues"],
  },
  {
    id: "cpp-syntax",
    slug: "syntax-initialization-and-control-flow",
    title: "表达式、初始化与控制流",
    summary: "从 JS/TS 的表达式经验进入 C++ 的初始化、作用域和编译期类型检查。",
    track: "cpp",
    order: 2,
    durationMinutes: 14,
    concepts: ["syntax", "initialization", "scope"],
    prerequisites: ["cpp-toolchain"],
  },
  {
    id: "cpp-types",
    slug: "types-const-and-value-semantics",
    title: "类型、const 与值语义",
    summary: "理解整数、浮点、枚举、const 和值拷贝，为后面的生命周期学习打底。",
    track: "cpp",
    order: 3,
    durationMinutes: 14,
    concepts: ["types", "const", "value semantics"],
    prerequisites: ["cpp-syntax"],
  },
  {
    id: "cpp-algorithms",
    slug: "algorithms-lambdas-and-callables",
    title: "算法、Lambda 与可调用对象",
    summary: "把数组 map/filter 经验迁移到 STL 算法、Lambda 和明确的迭代器边界。",
    track: "cpp",
    order: 7,
    durationMinutes: 16,
    concepts: ["algorithms", "lambda", "callables"],
    prerequisites: ["cpp-stl"],
  },
  {
    id: "cpp-move",
    slug: "move-semantics-and-ownership-transfer",
    title: "移动语义与所有权转移",
    summary: "理解拷贝、移动、右值和资源转移，知道什么时候避免不必要的数据复制。",
    track: "cpp",
    order: 9,
    durationMinutes: 18,
    concepts: ["move semantics", "rvalue", "ownership"],
    prerequisites: ["cpp-raii"],
  },
  {
    id: "cpp-exceptions",
    slug: "exceptions-errors-and-invariants",
    title: "异常、错误与不变量",
    summary: "比较异常、错误码和 optional，建立面向库与应用的失败语义。",
    track: "cpp",
    order: 11,
    durationMinutes: 16,
    concepts: ["exceptions", "error handling", "invariants"],
    prerequisites: ["cpp-move"],
  },
  {
    id: "cpp-ranges",
    slug: "ranges-views-and-pipeline-style",
    title: "Ranges、View 与管线式处理",
    summary: "用现代 C++ 的惰性 view 组织数据处理，并明确临时对象和生命周期。",
    track: "cpp",
    order: 13,
    durationMinutes: 18,
    concepts: ["ranges", "views", "lazy evaluation"],
    prerequisites: ["cpp-templates"],
  },
  {
    id: "cpp-io",
    slug: "files-formatting-and-serialization",
    title: "文件、格式化与序列化",
    summary: "处理文件流、文本和二进制边界，理解传感器消息为什么需要稳定格式。",
    track: "cpp",
    order: 14,
    durationMinutes: 16,
    concepts: ["filesystem", "streams", "serialization"],
    prerequisites: ["cpp-ranges"],
  },
  {
    id: "cpp-cmake-targets",
    slug: "cmake-targets-and-dependencies",
    title: "CMake Target 与依赖边界",
    summary: "从能编译程序升级到可维护 target，掌握 include、link 和传递依赖。",
    track: "cpp",
    order: 15,
    durationMinutes: 18,
    concepts: ["cmake", "targets", "dependencies"],
    prerequisites: ["cpp-io"],
  },
  {
    id: "cpp-sanitizers",
    slug: "sanitizers-and-memory-debugging",
    title: "Sanitizer 与内存调试",
    summary: "用 AddressSanitizer、UndefinedBehaviorSanitizer 和断言定位 C++ 隐蔽错误。",
    track: "cpp",
    order: 17,
    durationMinutes: 18,
    concepts: ["sanitizer", "undefined behavior", "debugging"],
    prerequisites: ["cpp-testing"],
  },
  {
    id: "cpp-sync",
    slug: "mutexes-atomics-and-thread-safety",
    title: "Mutex、Atomic 与线程安全",
    summary: "区分互斥、原子和无锁的适用边界，避免用 sleep 掩盖竞态问题。",
    track: "cpp",
    order: 19,
    durationMinutes: 18,
    concepts: ["mutex", "atomic", "thread safety"],
    prerequisites: ["cpp-concurrency"],
  },
  {
    id: "cpp-queues",
    slug: "message-queues-and-producer-consumer",
    title: "消息队列与生产者消费者",
    summary: "把传感器输入、处理任务和输出消息拆成有界队列，并处理背压和退出。",
    track: "cpp",
    order: 20,
    durationMinutes: 18,
    concepts: ["message queue", "producer consumer", "backpressure"],
    prerequisites: ["cpp-sync"],
  },
  {
    id: "cpp-realtime",
    slug: "timing-realtime-and-determinism",
    title: "时间、实时性与确定性",
    summary: "理解周期、抖动、截止时间和动态分配对机器人控制循环的影响。",
    track: "cpp",
    order: 22,
    durationMinutes: 18,
    concepts: ["realtime", "timing", "determinism"],
    prerequisites: ["cpp-performance"],
  },
  {
    id: "cpp-networking",
    slug: "networking-ipc-and-boundaries",
    title: "网络、IPC 与进程边界",
    summary: "比较 socket、共享内存、CLI 和消息中间件，选择合适的组件连接方式。",
    track: "cpp",
    order: 23,
    durationMinutes: 18,
    concepts: ["networking", "ipc", "protocols"],
    prerequisites: ["cpp-realtime"],
  },
  {
    id: "cpp-ros-workspace",
    slug: "ros2-workspaces-colcon-and-packages",
    title: "ROS 2 工作区、colcon 与包",
    summary: "从 CMake 项目进入 ROS 2 工作区，理解 package、colcon 和依赖声明。",
    track: "cpp",
    order: 24,
    durationMinutes: 18,
    concepts: ["ros2", "colcon", "packages"],
    prerequisites: ["cpp-networking"],
  },
  {
    id: "cpp-ros-topics",
    slug: "ros2-nodes-topics-and-qos",
    title: "ROS 2 Node、Topic 与 QoS",
    summary: "写出发布和订阅节点，理解消息流、队列深度和 QoS 对传感器数据的影响。",
    track: "cpp",
    order: 25,
    durationMinutes: 20,
    concepts: ["ros2", "nodes", "topics", "qos"],
    prerequisites: ["cpp-ros-workspace"],
  },
  {
    id: "cpp-ros-services",
    slug: "ros2-services-actions-and-feedback",
    title: "ROS 2 Service、Action 与反馈",
    summary: "区分短请求和长任务，设计可取消、带反馈和结果的机器人接口。",
    track: "cpp",
    order: 26,
    durationMinutes: 20,
    concepts: ["service", "action", "feedback"],
    prerequisites: ["cpp-ros-topics"],
  },
  {
    id: "cpp-ros-params",
    slug: "ros2-parameters-launch-and-lifecycle",
    title: "ROS 2 参数、Launch 与生命周期",
    summary: "把硬编码配置移到参数和 launch，并理解节点启动、暂停和关闭的状态。",
    track: "cpp",
    order: 27,
    durationMinutes: 20,
    concepts: ["parameters", "launch", "lifecycle"],
    prerequisites: ["cpp-ros-services"],
  },
  {
    id: "cpp-ros-tf2",
    slug: "ros2-tf2-urdf-and-rviz",
    title: "TF2、URDF 与 RViz",
    summary: "理解坐标系、机器人模型和可视化工具，建立传感器数据的空间直觉。",
    track: "cpp",
    order: 28,
    durationMinutes: 22,
    concepts: ["tf2", "urdf", "rviz"],
    prerequisites: ["cpp-ros-params"],
  },
  {
    id: "cpp-ros-bag",
    slug: "ros2-bag-testing-and-replay",
    title: "rosbag、回放与离线测试",
    summary: "记录和回放消息，把真实设备问题转成可重复的离线测试输入。",
    track: "cpp",
    order: 29,
    durationMinutes: 20,
    concepts: ["rosbag", "replay", "offline testing"],
    prerequisites: ["cpp-ros-tf2"],
  },
  {
    id: "cpp-ros-custom",
    slug: "ros2-custom-interfaces-and-contracts",
    title: "ROS 2 自定义接口与消息契约",
    summary: "从标准消息进入自定义 msg、srv 和 action，理解接口包与运行时包的边界。",
    track: "cpp",
    order: 30,
    durationMinutes: 20,
    concepts: ["ros2", "interfaces", "messages", "contracts"],
    prerequisites: ["cpp-ros-bag"],
  },
  {
    id: "cpp-ros-composition",
    slug: "ros2-composition-and-intra-process",
    title: "ROS 2 组件化与进程内通信",
    summary: "理解 component、容器和 intra-process communication，减少机器人节点间不必要的拷贝。",
    track: "cpp",
    order: 31,
    durationMinutes: 20,
    concepts: ["composition", "components", "intra-process"],
    prerequisites: ["cpp-ros-custom"],
  },
  {
    id: "cpp-ros-qos",
    slug: "ros2-qos-and-sensor-reliability",
    title: "ROS 2 QoS 与传感器可靠性",
    summary: "用可靠性、持久性、历史和深度配置传感器流，定位订阅端收不到数据的问题。",
    track: "cpp",
    order: 32,
    durationMinutes: 22,
    concepts: ["qos", "reliability", "sensor data"],
    prerequisites: ["cpp-ros-composition"],
  },
  {
    id: "cpp-ros-plugins",
    slug: "ros2-plugins-and-extensibility",
    title: "ROS 2 插件与可扩展节点",
    summary: "把算法实现和运行时装配分开，理解插件描述、工厂和可替换机器人能力。",
    track: "cpp",
    order: 33,
    durationMinutes: 22,
    concepts: ["plugins", "extensibility", "runtime loading"],
    prerequisites: ["cpp-ros-qos"],
  },
  {
    id: "cpp-ros-simulation",
    slug: "ros2-simulation-and-test-robots",
    title: "ROS 2 仿真与测试机器人",
    summary: "用仿真和固定输入验证节点行为，把硬件依赖降到最低并保留可复现测试。",
    track: "cpp",
    order: 34,
    durationMinutes: 22,
    concepts: ["simulation", "testing", "fixtures"],
    prerequisites: ["cpp-ros-plugins"],
  },
  {
    id: "cpp-tracing",
    slug: "ros2-tracing-and-diagnostics",
    title: "ROS 2 Tracing 与系统诊断",
    summary: "通过事件、时间戳和链路诊断节点延迟、丢消息和调度抖动。",
    track: "cpp",
    order: 35,
    durationMinutes: 22,
    concepts: ["tracing", "diagnostics", "latency"],
    prerequisites: ["cpp-ros-simulation"],
  },
  {
    id: "cpp-sensor-pipeline",
    slug: "project-sensor-message-pipeline",
    title: "小项目：传感器消息处理器",
    summary: "把传感器数据、QoS、所有权、诊断和消息循环组合成一个可测试的 C++ 处理器。",
    track: "cpp",
    order: 36,
    durationMinutes: 24,
    concepts: ["project", "sensors", "messages", "testing", "diagnostics"],
    prerequisites: ["cpp-tracing"],
  },
]; 

export const LESSONS: LessonMeta[] = [...commonLessons, ...pythonLessons, ...cppLessons];

export function getLessonById(id: string): LessonMeta | undefined {
  return LESSONS.find((lesson) => lesson.id === id);
}

export function getLessonsByTrack(track: Track): LessonMeta[] {
  return LESSONS.filter((lesson) => lesson.track === track).sort((a, b) => a.order - b.order);
}

export function getNextLesson(id: string): LessonMeta | undefined {
  const lesson = getLessonById(id);
  if (!lesson) return undefined;
  return getLessonsByTrack(lesson.track).find((candidate) => candidate.order === lesson.order + 1);
}

export function getPreviousLesson(id: string): LessonMeta | undefined {
  const lesson = getLessonById(id);
  if (!lesson) return undefined;
  return getLessonsByTrack(lesson.track).find((candidate) => candidate.order === lesson.order - 1);
}
